### ISSUE TITLE
Upload 2.1.0 artifacts to mavencentral

### ISSUE THREAD

**Issue by rkrombho** [elastic/elasticsearch-groovy#30]
Would be great if one could upload the 2.1.0 .jar file to MavenCentral or bintry.

**Comment by pickypg** [comment]
Hi @rkrombho, I'll be pushing them (2.0.1 and 2.1.0) today. I have been traveling and I was never able to publish the full upload (always on flaky WiFi).

Thanks for the reminder!

**Comment by scrotty** [comment]
Still don't see 2.1.0! With 2.0.0 I'm getting: 
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.deletebyquery.DeleteByQueryRequestExtensions]

Thanks in advance!

**Comment by AlexKovynev** [comment]
+1

**Comment by joergrech** [comment]
+1

**Comment by enp** [comment]
Still unavailable:

```
$ ./client.groovy 
Resolving dependency: org.elasticsearch#elasticsearch-groovy;2.1.0 {default=[default]}
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [unresolved dependency: org.elasticsearch#elasticsearch-groovy;2.1.0: not found]
```

**Comment by johngamarra** [comment]
+1

**Comment by pickypg** [comment]
All, I've uploaded the artifacts from 2.0.x to 2.1.x.

I'm running into an issue with my tests literally not running via Gradle for ES 2.2+, so that will be delayed, but I finally have gotten around to this one. Sorry it took so long!

**Comment by pickypg** [comment]
@scrotty 

> WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.deletebyquery.DeleteByQueryRequestExtensions]

This is because the `DeleteByQueryRequest` code is no longer included with ES by default. If you want this functionality (or for the warning to go away), then you can include the delete by query plugin.

```
org.elasticsearch.plugin:delete-by-query:${ES_VERSION}
```

Given that I don't want to encourage its use, I may remove it in a future version, which will remove this warning.

**Comment by enp** [comment]
Error is sill in the same place with delete-by-query plugin installed:

```
$ rpm -q elasticsearch
elasticsearch-2.1.1-1

$ /usr/share/elasticsearch/bin/plugin list
Installed plugins in /usr/share/elasticsearch/plugins:
    - head
    - hq
    - delete-by-query

$ cat node.groovy 
#!/usr/bin/env groovy

@Grapes(@Grab(group='org.elasticsearch', module='elasticsearch-groovy', version='2.1.0'))
import org.elasticsearch.groovy.client.GClient
import org.elasticsearch.groovy.node.GNode
import static org.elasticsearch.groovy.node.GNodeBuilder.nodeBuilder

GNode node = nodeBuilder().node();
GClient client = node.client();

node.close();

$ ./node.groovy 
фев 03, 2016 8:24:33 AM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [elasticsearch-groovy-module] - Unable to load extension class [org.elasticsearch.groovy.action.deletebyquery.DeleteByQueryRequestExtensions]
Caught: BUG! exception in phase 'conversion' in source unit '/home/enp/twibo/node.groovy' # Licensed to the Apache Software Foundation (ASF) under one or more
BUG! exception in phase 'conversion' in source unit '/home/enp/twibo/node.groovy' # Licensed to the Apache Software Foundation (ASF) under one or more
Caused by: java.lang.ClassNotFoundException: # Licensed to the Apache Software Foundation (ASF) under one or more

```

**Comment by enp** [comment]
Even adding this plugin to groovy script by:

```
@Grapes(@Grab(group='org.elasticsearch.plugin', module='delete-by-query', version='2.1.1'))
import org.elasticsearch.groovy.action.deletebyquery.DeleteByQueryRequestExtensions
```

will not work because there are no such class:

```
$ unzip -l /home/enp/.groovy/grapes/org.elasticsearch.plugin/delete-by-query/jars/delete-by-query-2.1.1.jar | grep DeleteByQueryRequestExtensions
$ 
```

So, groovy client for ES is completely broken now. This is now only warning, this prevents to run any groovy code as above.

**Comment by pickypg** [comment]
@enp 

The error you're seeing is because you're using `Grab` and not removing `groovy-all`:

```java
@Grab(group='org.elasticsearch', module='elasticsearch-groovy', version='1.7.1') 
@GrabExclude('org.codehaus.groovy:groovy-all')
```

As a side note, your use of `G`* classes suggests that it's out of date as well.

To test that ES Groovy 2.1.1 is indeed working, I quickly ran:

```groovy
package org.elastic.test

import org.elasticsearch.client.Client
import org.elasticsearch.client.transport.TransportClient
import org.elasticsearch.common.settings.Settings
import org.elasticsearch.common.transport.InetSocketTransportAddress

import org.elasticsearch.action.search.SearchResponse

import java.net.InetAddress

class Main {
    static void main(String[] args) {
        TransportClient client = TransportClient.builder().settings(Settings.settingsBuilder {
            cluster.name = "es-2.1.1"
        }).build()

        // identical to the Java client:
        client.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300))

        SearchResponse response = client.searchSync {
            indices "_all"
        }

        println "${response.hits.hits.length}"

        client.close()
    }
}
```

I used this Gradle build file:

```gradle
apply plugin: 'application'
apply plugin: 'groovy'

mainClassName = 'org.elastic.test.Main'

repositories {
  mavenCentral()
}

dependencies {
  compile "org.elasticsearch:elasticsearch-groovy:2.1.1"
}
```

> Error is sill in the same place with delete-by-query plugin installed:

The **Warning** does indeed still happen with it. I apparently removed the `DeleteByQuery` code back around ES 1.5 when it was removed from the codebase. Now that it was brought back, I need to rethink that code though. I may make my own plugin to support it for those few that actually want it; I'll make a separate issue for it.

All the warning is saying is that the _Extension Module_ does not apply to anything or it does not exist. In this case it's both, but that has no negative impact beyond the annoying log line.

**Comment by pickypg** [comment]
@enp Also, have a look over the basic documentation for the Groovy client. It has changed dramatically since I took it over starting in the 1.4.x days.

https://github.com/elastic/elasticsearch-groovy/tree/master/docs

I definitely need to add more to these and update them. With Elastic{ON} around the corner, I should hopefully have some time to do that.

**Comment by enp** [comment]
Thanks for gradle example and especially for excluding hint. Is this grab-specific issue an can be resolved only in grab code? Where can I see groovydoc for es client?

**Comment by pickypg** [comment]
@enp 

> Is this grab-specific issue an can be resolved only in grab code?

Yeah, the issue that you're seeing is specific to `Grab` (see issue #29 where someone pointed it out to me and we worked toward working around it, including a JIRA issue for Groovy to stop it from trying to add Groovy to its own classpath).

> Where can I see groovydoc for es client?

I don't host it online anywhere, but that's a good idea because I do publish them with every release. I'll make an issue for that (#34).
